### ISSUE TITLE
Fatal Error: Cannot Declare Class Flarum\Forum\ValidateCustomLess due to Name Conflict

### ISSUE THREAD

**Issue by scysys** [startracex/flarum-dark#4]
`PHP Fatal error:  Cannot declare class Flarum\Forum\ValidateCustomLess, because the name is already in use in /home/pzyqduzg/FLARUM/vendor/startracex/flarum-dark/src/Overrides/Forum/ValidateCustomLess.php on line 28`

Flarum: 1.8.5
PHP: 8.3.8

Thanks :)

**Comment by startracex** [comment]
Try to remove fof/nightmode

```sh
composer remove fof/nightmode
```
